package ghostFactoryPattern;

/**
 * The factory which interacts with the user.
 * @author alex
 *
 */
public class GhostFactory {
	public GhostGenerator generate = new GhostGenerator(); 
	
	/**
	 * Returns the specified ghost from the factory which is generated by the generator object. 
	 * @param ghostNumber - which ghost to generate.
	 * @return ghost - the ghost generated.
	 * @see Ghost
	 */
	public Ghost getGhost(int ghostNumber) {
		Ghost ghost = null;
		switch (ghostNumber) {
			case 1:
				ghost = generate.produce(1);
				break;
			case 2:
				ghost = generate.produce(2);
				break;
			case 3:
				ghost = generate.produce(3);
				break;
			case 4:
				ghost = generate.produce(4);
				break;
			case 5:
				ghost = generate.produce(5);
				break;
		}
		return ghost;
	}
}
